"""
Generates the speak_interactive.csv mock data file used by SpeakInteractivePage.

The CSV format mirrors write_interactive exactly — same column structure —
but without the 'Character Limit' column since speaking has no character limit.

Each exercise has:
  - A scenario (title + description)
  - Up to 3 exchanges: each exchange = bot speaks → user responds by speaking
  - Bilingual content (FR + EN) for all fields

Run from workspace root:
  python language-app/generate_speak_interactive_csv.py

Or from the language-app directory:
  python generate_speak_interactive_csv.py
"""

import csv
import os

OUTPUT = os.path.join(
    os.path.dirname(__file__),
    "public", "mock-data", "practice", "speaking", "speak_interactive.csv"
)

HEADER = [
    "ExerciseID", "Question Type", "Exercise Tag", "Level", "Difficulty", "Time",
    "Scenario Title_FR", "Scenario Title_EN",
    "Scenario_FR", "Scenario_EN",
    "Speaker_1_FR", "Speaker_1_EN",
    "Prompt_1_FR", "Prompt_1_EN",
    "Sample_1_FR", "Sample_1_EN",
    "Min_Words_1",
    "Speaker_2_FR", "Speaker_2_EN",
    "Prompt_2_FR", "Prompt_2_EN",
    "Sample_2_FR", "Sample_2_EN",
    "Min_Words_2",
    "Speaker_3_FR", "Speaker_3_EN",
    "Prompt_3_FR", "Prompt_3_EN",
    "Sample_3_FR", "Sample_3_EN",
    "Min_Words_3",
]

EXERCISES = [
    {
        "ExerciseID": "SI001",
        "Question Type": "Interactive Speaking",
        "Exercise Tag": "Professional communication",
        "Level": "A1",
        "Difficulty": "Easy",
        "Time": "300",
        "Scenario Title_FR": "Chez le médecin",
        "Scenario Title_EN": "At the Doctor",
        "Scenario_FR": "Tu as rendez-vous chez le médecin pour un contrôle.",
        "Scenario_EN": "You have an appointment at the doctor for a check-up.",
        "Speaker_1_FR": "Bonjour ! Je suis le docteur Martin. Comment vous sentez-vous aujourd'hui ?",
        "Speaker_1_EN": "Hello! I am Doctor Martin. How are you feeling today?",
        "Prompt_1_FR": "Décrivez comment vous vous sentez en ce moment.",
        "Prompt_1_EN": "Describe how you are feeling right now.",
        "Sample_1_FR": "Je ne me sens pas très bien. J'ai mal à la tête et je suis fatigué depuis deux jours.",
        "Sample_1_EN": "I don't feel very well. I have a headache and I have been tired for two days.",
        "Min_Words_1": "6",
        "Speaker_2_FR": "Je vois. Depuis combien de temps avez-vous ces symptômes ?",
        "Speaker_2_EN": "I see. How long have you had these symptoms?",
        "Prompt_2_FR": "Expliquez depuis quand vous avez ces problèmes.",
        "Prompt_2_EN": "Explain how long you have had these problems.",
        "Sample_2_FR": "J'ai ces symptômes depuis environ trois jours. Je pense que j'ai peut-être attrapé un rhume.",
        "Sample_2_EN": "I have had these symptoms for about three days. I think I may have caught a cold.",
        "Min_Words_2": "6",
        "Speaker_3_FR": "Très bien. Avez-vous pris des médicaments ?",
        "Speaker_3_EN": "Very well. Have you taken any medication?",
        "Prompt_3_FR": "Dites si vous avez pris des médicaments et lesquels.",
        "Prompt_3_EN": "Say whether you have taken any medication and which ones.",
        "Sample_3_FR": "Non je n'ai pas encore pris de médicaments. Je voulais d'abord consulter un médecin.",
        "Sample_3_EN": "No I have not taken any medication yet. I wanted to consult a doctor first.",
        "Min_Words_3": "5",
    },
    {
        "ExerciseID": "SI002",
        "Question Type": "Interactive Speaking",
        "Exercise Tag": "Professional communication",
        "Level": "A1",
        "Difficulty": "Easy",
        "Time": "300",
        "Scenario Title_FR": "À la boulangerie",
        "Scenario Title_EN": "At the Bakery",
        "Scenario_FR": "Tu entres dans une boulangerie pour acheter du pain et des croissants.",
        "Scenario_EN": "You enter a bakery to buy bread and croissants.",
        "Speaker_1_FR": "Bonjour ! Qu'est-ce que je vous sers aujourd'hui ?",
        "Speaker_1_EN": "Hello! What can I get you today?",
        "Prompt_1_FR": "Commandez ce que vous voulez acheter à la boulangerie.",
        "Prompt_1_EN": "Order what you want to buy at the bakery.",
        "Sample_1_FR": "Bonjour ! Je voudrais une baguette et deux croissants s'il vous plaît.",
        "Sample_1_EN": "Hello! I would like a baguette and two croissants please.",
        "Min_Words_1": "5",
        "Speaker_2_FR": "Bien sûr ! Vous désirez autre chose ? Nous avons aussi de très bons pains au chocolat.",
        "Speaker_2_EN": "Of course! Would you like anything else? We also have very good pain au chocolat.",
        "Prompt_2_FR": "Répondez si vous voulez autre chose ou non.",
        "Prompt_2_EN": "Respond whether you want anything else or not.",
        "Sample_2_FR": "Oui je vais prendre deux pains au chocolat aussi. C'est pour offrir à ma famille.",
        "Sample_2_EN": "Yes I will take two pain au chocolat as well. It is a gift for my family.",
        "Min_Words_2": "5",
        "Speaker_3_FR": "Ça fait cinq euros cinquante. Vous payez comment ?",
        "Speaker_3_EN": "That comes to five euros fifty. How will you pay?",
        "Prompt_3_FR": "Dites comment vous allez payer.",
        "Prompt_3_EN": "Say how you will pay.",
        "Sample_3_FR": "Je vais payer par carte s'il vous plaît. Voici ma carte bancaire.",
        "Sample_3_EN": "I will pay by card please. Here is my bank card.",
        "Min_Words_3": "4",
    },
    {
        "ExerciseID": "SI003",
        "Question Type": "Interactive Speaking",
        "Exercise Tag": "Professional communication",
        "Level": "A1",
        "Difficulty": "Easy",
        "Time": "300",
        "Scenario Title_FR": "Réserver un hôtel",
        "Scenario Title_EN": "Booking a Hotel",
        "Scenario_FR": "Tu appelles un hôtel pour réserver une chambre pour le week-end.",
        "Scenario_EN": "You call a hotel to book a room for the weekend.",
        "Speaker_1_FR": "Bonjour hôtel Le Soleil. Comment puis-je vous aider ?",
        "Speaker_1_EN": "Hello Hotel Le Soleil. How can I help you?",
        "Prompt_1_FR": "Dites que vous voulez réserver une chambre et pour combien de nuits.",
        "Prompt_1_EN": "Say that you want to book a room and for how many nights.",
        "Sample_1_FR": "Bonjour ! Je voudrais réserver une chambre pour deux nuits s'il vous plaît. Du vendredi au dimanche.",
        "Sample_1_EN": "Hello! I would like to book a room for two nights please. From Friday to Sunday.",
        "Min_Words_1": "7",
        "Speaker_2_FR": "Bien sûr. Pour combien de personnes et quel type de chambre souhaitez-vous ?",
        "Speaker_2_EN": "Of course. For how many people and what type of room would you like?",
        "Prompt_2_FR": "Précisez le nombre de personnes et le type de chambre.",
        "Prompt_2_EN": "Specify the number of people and the type of room.",
        "Sample_2_FR": "C'est pour deux personnes. Nous préférons une chambre double avec salle de bain privée si possible.",
        "Sample_2_EN": "It is for two people. We prefer a double room with a private bathroom if possible.",
        "Min_Words_2": "7",
        "Speaker_3_FR": "Parfait. Puis-je avoir votre nom et un numéro de téléphone ?",
        "Speaker_3_EN": "Perfect. May I have your name and a phone number?",
        "Prompt_3_FR": "Donnez votre nom et votre numéro de téléphone.",
        "Prompt_3_EN": "Give your name and phone number.",
        "Sample_3_FR": "Mon nom est Dupont et mon numéro est le zéro six douze trente-quatre cinquante-six.",
        "Sample_3_EN": "My name is Dupont and my number is zero six twelve thirty-four fifty-six.",
        "Min_Words_3": "5",
    },
    {
        "ExerciseID": "SI004",
        "Question Type": "Interactive Speaking",
        "Exercise Tag": "Professional communication",
        "Level": "A2",
        "Difficulty": "Easy",
        "Time": "300",
        "Scenario Title_FR": "Demander son chemin",
        "Scenario Title_EN": "Asking for Directions",
        "Scenario_FR": "Tu es perdu dans une ville et tu demandes ton chemin à un passant.",
        "Scenario_EN": "You are lost in a city and ask a passer-by for directions.",
        "Speaker_1_FR": "Excusez-moi ! Vous avez l'air perdu. Je peux vous aider ?",
        "Speaker_1_EN": "Excuse me! You look lost. Can I help you?",
        "Prompt_1_FR": "Expliquez que vous cherchez la gare et que vous êtes perdu.",
        "Prompt_1_EN": "Explain that you are looking for the train station and that you are lost.",
        "Sample_1_FR": "Oui merci ! Je cherche la gare centrale mais je ne sais pas du tout où elle se trouve.",
        "Sample_1_EN": "Yes thank you! I am looking for the central station but I have no idea where it is.",
        "Min_Words_1": "7",
        "Speaker_2_FR": "La gare est à environ dix minutes à pied. Vous prenez cette rue puis vous tournez à gauche.",
        "Speaker_2_EN": "The station is about ten minutes on foot. You take this street then turn left.",
        "Prompt_2_FR": "Répétez les directions pour confirmer que vous avez compris.",
        "Prompt_2_EN": "Repeat the directions to confirm you understood.",
        "Sample_2_FR": "D'accord donc je prends cette rue et je tourne à gauche. Est-ce qu'il y a un repère visible ?",
        "Sample_2_EN": "OK so I take this street and turn left. Is there a visible landmark?",
        "Min_Words_2": "7",
        "Speaker_3_FR": "Oui vous verrez une grande pharmacie au coin. La gare est juste en face.",
        "Speaker_3_EN": "Yes you will see a large pharmacy on the corner. The station is right opposite.",
        "Prompt_3_FR": "Remerciez la personne et dites au revoir.",
        "Prompt_3_EN": "Thank the person and say goodbye.",
        "Sample_3_FR": "Merci beaucoup c'est très gentil de votre part. Bonne journée à vous !",
        "Sample_3_EN": "Thank you very much that is very kind of you. Have a good day!",
        "Min_Words_3": "5",
    },
    {
        "ExerciseID": "SI005",
        "Question Type": "Interactive Speaking",
        "Exercise Tag": "Daily life",
        "Level": "A1",
        "Difficulty": "Easy",
        "Time": "300",
        "Scenario Title_FR": "Au café",
        "Scenario Title_EN": "At the Café",
        "Scenario_FR": "Tu es dans un café et tu commandes quelque chose à boire.",
        "Scenario_EN": "You are in a café and you order something to drink.",
        "Speaker_1_FR": "Bonjour ! Qu'est-ce que vous prenez ?",
        "Speaker_1_EN": "Hello! What would you like?",
        "Prompt_1_FR": "Commandez une boisson et demandez le prix.",
        "Prompt_1_EN": "Order a drink and ask for the price.",
        "Sample_1_FR": "Bonjour ! Je voudrais un café au lait s'il vous plaît. C'est combien ?",
        "Sample_1_EN": "Hello! I would like a café au lait please. How much is it?",
        "Min_Words_1": "6",
        "Speaker_2_FR": "C'est deux euros cinquante. Vous voulez aussi quelque chose à manger ?",
        "Speaker_2_EN": "That is two euros fifty. Would you also like something to eat?",
        "Prompt_2_FR": "Répondez si vous voulez manger quelque chose ou non.",
        "Prompt_2_EN": "Respond whether you want something to eat or not.",
        "Sample_2_FR": "Non merci. Juste le café pour l'instant. Peut-être un croissant plus tard.",
        "Sample_2_EN": "No thank you. Just the coffee for now. Maybe a croissant later.",
        "Min_Words_2": "6",
        "Speaker_3_FR": "Bien sûr. Voici votre café. Bonne journée !",
        "Speaker_3_EN": "Of course. Here is your coffee. Have a good day!",
        "Prompt_3_FR": "Remerciez le serveur.",
        "Prompt_3_EN": "Thank the waiter.",
        "Sample_3_FR": "Merci beaucoup. C'est très bon. Bonne journée à vous aussi !",
        "Sample_3_EN": "Thank you very much. It is very good. Have a good day to you too!",
        "Min_Words_3": "4",
    },
    {
        "ExerciseID": "SI006",
        "Question Type": "Interactive Speaking",
        "Exercise Tag": "Daily life",
        "Level": "A2",
        "Difficulty": "Medium",
        "Time": "300",
        "Scenario Title_FR": "Faire les courses",
        "Scenario Title_EN": "Grocery Shopping",
        "Scenario_FR": "Tu es au supermarché et tu demandes de l'aide à un employé.",
        "Scenario_EN": "You are at the supermarket and you ask an employee for help.",
        "Speaker_1_FR": "Bonjour ! Je peux vous aider à trouver quelque chose ?",
        "Speaker_1_EN": "Hello! Can I help you find something?",
        "Prompt_1_FR": "Demandez où se trouvent les produits laitiers.",
        "Prompt_1_EN": "Ask where the dairy products are.",
        "Sample_1_FR": "Bonjour ! Oui s'il vous plaît. Je cherche les produits laitiers. Où sont-ils ?",
        "Sample_1_EN": "Hello! Yes please. I am looking for the dairy products. Where are they?",
        "Min_Words_1": "7",
        "Speaker_2_FR": "Les produits laitiers sont au fond du magasin à droite. Vous cherchez quelque chose en particulier ?",
        "Speaker_2_EN": "The dairy products are at the back of the store on the right. Are you looking for something in particular?",
        "Prompt_2_FR": "Dites ce que vous cherchez exactement.",
        "Prompt_2_EN": "Say what you are looking for exactly.",
        "Sample_2_FR": "Je cherche du fromage et du beurre. Est-ce que vous avez du fromage de chèvre ?",
        "Sample_2_EN": "I am looking for cheese and butter. Do you have goat's cheese?",
        "Min_Words_2": "7",
        "Speaker_3_FR": "Oui bien sûr. Le fromage de chèvre est dans le rayon fromages juste à côté.",
        "Speaker_3_EN": "Yes of course. The goat's cheese is in the cheese section right next to it.",
        "Prompt_3_FR": "Remerciez l'employé et dites que vous allez y aller.",
        "Prompt_3_EN": "Thank the employee and say you will go there.",
        "Sample_3_FR": "Parfait merci beaucoup. Je vais y aller tout de suite. Bonne journée !",
        "Sample_3_EN": "Perfect thank you very much. I will go there right away. Have a good day!",
        "Min_Words_3": "6",
    },
    {
        "ExerciseID": "SI007",
        "Question Type": "Interactive Speaking",
        "Exercise Tag": "Travel",
        "Level": "A2",
        "Difficulty": "Medium",
        "Time": "300",
        "Scenario Title_FR": "À la gare",
        "Scenario Title_EN": "At the Train Station",
        "Scenario_FR": "Tu es à la gare et tu achètes un billet de train.",
        "Scenario_EN": "You are at the train station and you buy a train ticket.",
        "Speaker_1_FR": "Bonjour ! Je peux vous aider ?",
        "Speaker_1_EN": "Hello! Can I help you?",
        "Prompt_1_FR": "Demandez un billet pour Paris et précisez la date.",
        "Prompt_1_EN": "Ask for a ticket to Paris and specify the date.",
        "Sample_1_FR": "Bonjour ! Je voudrais un billet pour Paris s'il vous plaît. Pour demain matin.",
        "Sample_1_EN": "Hello! I would like a ticket to Paris please. For tomorrow morning.",
        "Min_Words_1": "7",
        "Speaker_2_FR": "Bien sûr. Aller simple ou aller-retour ? Et vous préférez quelle heure ?",
        "Speaker_2_EN": "Of course. Single or return? And what time do you prefer?",
        "Prompt_2_FR": "Précisez si c'est aller simple ou retour et l'heure souhaitée.",
        "Prompt_2_EN": "Specify if it is single or return and the preferred time.",
        "Sample_2_FR": "Un aller-retour s'il vous plaît. Je préfère partir vers neuf heures du matin.",
        "Sample_2_EN": "A return ticket please. I prefer to leave around nine in the morning.",
        "Min_Words_2": "7",
        "Speaker_3_FR": "Il y a un train à neuf heures quinze. Ça vous convient ? C'est soixante euros.",
        "Speaker_3_EN": "There is a train at nine fifteen. Does that suit you? It is sixty euros.",
        "Prompt_3_FR": "Confirmez et demandez si vous pouvez payer par carte.",
        "Prompt_3_EN": "Confirm and ask if you can pay by card.",
        "Sample_3_FR": "Oui parfait. Est-ce que je peux payer par carte bancaire s'il vous plaît ?",
        "Sample_3_EN": "Yes perfect. Can I pay by bank card please?",
        "Min_Words_3": "6",
    },
    {
        "ExerciseID": "SI008",
        "Question Type": "Interactive Speaking",
        "Exercise Tag": "Social situations",
        "Level": "B1",
        "Difficulty": "Medium",
        "Time": "300",
        "Scenario Title_FR": "Chez un ami",
        "Scenario Title_EN": "At a Friend's Place",
        "Scenario_FR": "Tu es invité chez un ami pour dîner et vous discutez de vos projets.",
        "Scenario_EN": "You are invited to a friend's place for dinner and you discuss your plans.",
        "Speaker_1_FR": "Alors comment ça va ? Tu as l'air fatigué ce soir.",
        "Speaker_1_EN": "So how are you? You look tired this evening.",
        "Prompt_1_FR": "Expliquez pourquoi vous êtes fatigué et parlez de votre semaine.",
        "Prompt_1_EN": "Explain why you are tired and talk about your week.",
        "Sample_1_FR": "Oui je suis épuisé. J'ai eu une semaine très chargée au travail. On a eu beaucoup de réunions.",
        "Sample_1_EN": "Yes I am exhausted. I had a very busy week at work. We had a lot of meetings.",
        "Min_Words_1": "8",
        "Speaker_2_FR": "Je comprends. Et tu as des projets pour le week-end prochain ?",
        "Speaker_2_EN": "I understand. And do you have plans for next weekend?",
        "Prompt_2_FR": "Parlez de vos projets pour le week-end.",
        "Prompt_2_EN": "Talk about your plans for the weekend.",
        "Sample_2_FR": "Oui je pense aller à la campagne avec ma famille. On veut se reposer et profiter de la nature.",
        "Sample_2_EN": "Yes I am thinking of going to the countryside with my family. We want to rest and enjoy nature.",
        "Min_Words_2": "8",
        "Speaker_3_FR": "Ça a l'air super ! Tu pars vendredi soir ou samedi matin ?",
        "Speaker_3_EN": "That sounds great! Are you leaving Friday evening or Saturday morning?",
        "Prompt_3_FR": "Précisez quand vous partez et pour combien de temps.",
        "Prompt_3_EN": "Specify when you are leaving and for how long.",
        "Sample_3_FR": "On part samedi matin de bonne heure. On revient dimanche soir. Deux jours c'est parfait pour se ressourcer.",
        "Sample_3_EN": "We leave Saturday morning early. We come back Sunday evening. Two days is perfect to recharge.",
        "Min_Words_3": "8",
    },
]


def main():
    os.makedirs(os.path.dirname(OUTPUT), exist_ok=True)

    with open(OUTPUT, "w", newline="", encoding="utf-8-sig") as f:
        writer = csv.DictWriter(f, fieldnames=HEADER)
        writer.writeheader()
        writer.writerows(EXERCISES)

    print(f"Written {len(EXERCISES)} exercises to {OUTPUT}")


if __name__ == "__main__":
    main()
